exercism/vlang

- .github/workflows/test.yml
- bin/test
- exercises/practice/hello-world/run_test.v
It is working on all architectures on [my fork](https://github.com/1ethanhansen/vlang/actions/runs/3446462240/jobs/5751393289)
> feat: Add CI

- exercises/practice/space-age/run_test.v
now if the function does not return an error for the sun, the test fails. I don't believe it did previously
> fix: better way to test error on space-age

- exercises/practice/nucleotide-count/.meta/config.json
Did not mean to push to main! i had typed out git checkout branch add-nucleotide and never hit enter or it didn't register. @ErikSchierboom would it be possible to protect the main branch so it can't be pushed to directly and needs to have a PR into it to merge please? I don't have access to those settings.
> fix: wrong file name in nucleotide

- bin/test
This PR ensures that CI fails when one of the exemplar/example implementations does not pass the tests
Noted by http://forum.exercism.org/t/exercisms-ci-and-me-2-2-3/2800/4
Side note: the robot-name tests appear to be flakey, so you might want to look into that
> ci: fail when one of the exercise's example/exemplar does not pass the tests

- config.json
- exercises/practice/secret-handshake/.docs/instructions.md
- exercises/practice/secret-handshake/.meta/config.json
- exercises/practice/secret-handshake/.meta/example.v
- exercises/practice/secret-handshake/.meta/tests.toml
- exercises/practice/secret-handshake/run_test.v
- exercises/practice/secret-handshake/secret_handshake.v
I speedran the V track this weekend so I figured I'd start adding some exercises. :)
Starting with the ones that were selected for the [12in23 challenge](https://exercism.org/challenges/12in23), Secret Handshake is nice for practicing bit manipulation but I also included an enum for the commands because it makes the solution look better.
Also, I think it's a good idea to start populating the `practices` and `prerequisites` lists before we end up with a plethora of exercises we'd need to revise. I might work on a PR to add them to all the exercises.
> Add exercise `secret-handshake`

- exercises/practice/grains/.meta/example.v
- exercises/practice/grains/grains.v
Why? Right now there is an overflow situation, that accidently doesn't show up, since vlang treats 2^64 as 0 adding -1 seems to be the same as 2^64-1.
> [~] fix: [grains] Grains template now uses u64 type, that can hold expected 2^64-1

- exercises/practice/nth-prime/run_test.v
I figured this was an oversight so thought it was a good idea to remove it since it was adding noise to the test results.
> nth-prime: remove test that only prints the first ten primes

- README.md
- bin/bootstrap_practice_exercise.sh
- config.json
I saw a version of this in other tracks and thought it was a must-have. It will generate the `.docs` and `.meta` directories with all the required files, and also create the V files so you can jump directly into writing the code. In the future, this can be updated to generate the V test cases and the main public function(s) for the exercise as well, which will save even more time.
The `config.json` file gets formatted by `jq` when running the script, so I'm adding the formatted file along with it.
> Add script to bootstrap practice exercise

- config.json
- exercises/practice/linked-list/.docs/instructions.append.md
- exercises/practice/linked-list/.docs/instructions.md
- exercises/practice/linked-list/.meta/config.json
- exercises/practice/linked-list/.meta/example.v
- exercises/practice/linked-list/.meta/tests.toml
- exercises/practice/linked-list/linked-list.v
- exercises/practice/linked-list/run_test.v
As in #63 , this is an attempt to add the final recommended exercise. I saw @natanaelsirqueira had been adding them steadily and thought I could do some extra practice by lending a hand. Now I see I'm a few hours late!
I went with `linked-list` instead of `simple-linked-list`, but perhaps it's best to only have one per track? Looking at the implementations, my use of unsafe nil pointers (and discovery of a compiler bug if I don't) might mean `linked-list` is a little more problematic as an exercise for V at the moment. Although, this might simply be a reflection of my naivety with V, and Natanael's trick of keeping a `len` counter might work similarly.
The other discrepancy between the two is that I rated `linked-list` a difficulty 5 (after contemplating a 4) and Natanael gave …
> Add exercise `linked-list`

- config.json
- exercises/practice/etl/.docs/instructions.md
- exercises/practice/etl/.docs/introduction.md
- exercises/practice/etl/.meta/config.json
- exercises/practice/etl/.meta/example.v
- exercises/practice/etl/.meta/tests.toml
- exercises/practice/etl/etl.v
- exercises/practice/etl/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/etl/canonical-data.json
> feat: Add exercise ETL (closes #86)

- config.json
- exercises/practice/variable-length-quantity/.docs/instructions.md
- exercises/practice/variable-length-quantity/.meta/config.json
- exercises/practice/variable-length-quantity/.meta/example.v
- exercises/practice/variable-length-quantity/.meta/tests.toml
- exercises/practice/variable-length-quantity/run_test.v
- exercises/practice/variable-length-quantity/variable-length-quantity.v
Test cases use hexadecimal literals, as suggested in
https://github.com/exercism/problem-specifications/blob/main/exercises/variable-length-quantity/canonical-data.json
Function and argument names, and test cases, are taken from the above file.
> feat: Add Variable Length Quantity (closes #93)

- config.json
- exercises/practice/atbash-cipher/.docs/instructions.md
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/atbash-cipher/.meta/example.v
- exercises/practice/atbash-cipher/.meta/tests.toml
- exercises/practice/atbash-cipher/atbash-cipher.v
- exercises/practice/atbash-cipher/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/atbash-cipher/canonical-data.json
> feat: Add Atbash Cipher (closes #102)

- config.json
- exercises/practice/acronym/.docs/instructions.md
- exercises/practice/acronym/.meta/config.json
- exercises/practice/acronym/.meta/example.v
- exercises/practice/acronym/.meta/tests.toml
- exercises/practice/acronym/acronym.v
- exercises/practice/acronym/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/acronym/canonical-data.json
> feat: Add Acronym (closes #107)

- config.json
- exercises/practice/resistor-color-duo/.docs/instructions.md
- exercises/practice/resistor-color-duo/.meta/config.json
- exercises/practice/resistor-color-duo/.meta/example.v
- exercises/practice/resistor-color-duo/.meta/tests.toml
- exercises/practice/resistor-color-duo/resistor-color-duo.v
- exercises/practice/resistor-color-duo/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/resistor-color-duo/canonical-data.json
> feat: Add Resistor Color Duo (closes #117)

- exercises/practice/say/.meta/example.v
Fix a compile error in example solution.
(With a recent update to the V compiler, the example solution for the Say exercise no longer compiles.)
> fix: Update handling of options in Say

- config.json
- exercises/practice/rail-fence-cipher/.docs/instructions.md
- exercises/practice/rail-fence-cipher/.meta/config.json
- exercises/practice/rail-fence-cipher/.meta/example.v
- exercises/practice/rail-fence-cipher/.meta/tests.toml
- exercises/practice/rail-fence-cipher/rail-fence-cipher.v
- exercises/practice/rail-fence-cipher/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/rail-fence-cipher/canonical-data.json
> feat: Add Rail Fence Cipher (closes #91)

- config.json
- exercises/practice/word-search/.docs/instructions.md
- exercises/practice/word-search/.meta/config.json
- exercises/practice/word-search/.meta/example.v
- exercises/practice/word-search/.meta/tests.toml
- exercises/practice/word-search/run_test.v
- exercises/practice/word-search/word-search.v
https://github.com/exercism/problem-specifications/blob/main/exercises/word-search/canonical-data.json
_Option C_ from #124 comments is implemented: we return a map, with `none` used for words not present in the grid.
> Add Word Search practice exercise (closes #124)

- exercises/practice/clock/run_test.v
For the following test case:
```vlang
fn test_negative_hour_and_minute_roll_over() {
c := new_clock(2, -60)
assert c.string() == '01:00'
}
```
The description seems to imply that the hour should be negative, only the minute argument is. I suspect that this is a cut & paste error from the test case `test_negative_60_minutes_previous_hour` on lines 88-91
```vlang
fn test_negative_60_minutes_previous_hour() {
c := new_clock(2, -60)
assert c.string() == '01:00'
}
```
> Possible error in vlang test suite for clock exercise

- config.json
- exercises/practice/affine-cipher/.docs/instructions.md
- exercises/practice/affine-cipher/.meta/config.json
- exercises/practice/affine-cipher/.meta/example.v
- exercises/practice/affine-cipher/.meta/tests.toml
- exercises/practice/affine-cipher/affine-cipher.v
- exercises/practice/affine-cipher/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/affine-cipher/canonical-data.json
closes #114
> feat: Add Affine Cipher (closes #114)

- README.md
'(' used instead of '[' preventing markdown rendering the enclosed text as a link.
> Correcting minor typo in markdown

- config.json
- exercises/practice/armstrong-numbers/.docs/instructions.md
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/example.v
- exercises/practice/armstrong-numbers/.meta/tests.toml
- exercises/practice/armstrong-numbers/armstrong-numbers.v
- exercises/practice/armstrong-numbers/run_test.v
Two of the suggested tests; "Armstrong number containing seven zeroes" &
"The largest and last Armstrong number" not implemented as these tests are
involve numbers which require 128 bits, not yet supported by V.
According to [wikipedia](https://en.wikipedia.org/wiki/Narcissistic_number#Extension_to_negative_integers) narcissistic numbers can be negative.
$$
-8 = -8^1
$$
$$
-371 = -3^3 + -7^3 + -1^3
$$
$$
-9475 \neq -9^4 + -4^4 + -7^4 + -5^4
$$
$$
-9474 = -9^4 + -4^4 + -7^4 + -4^4
$$
If this is the case, do the test cases need updating?
> Adding Armstrong numbers to V practice questions

- config.json
- exercises/practice/list-ops/.docs/instructions.md
- exercises/practice/list-ops/.meta/config.json
- exercises/practice/list-ops/.meta/example.v
- exercises/practice/list-ops/.meta/tests.toml
- exercises/practice/list-ops/list-ops.v
- exercises/practice/list-ops/run_test.v
Found this initially difficult. Though once I understood that an array could be a generic parameter, everything dropped into place. I've given this a difficulty rating of 5. What do you think?
This exercise requires an understanding of generics and touches on some aspects of functional programming techniques (mapping, filtering, folding, ..., etc). Do these topics need to be mentioned anywhere as a prerequisite in the `prerequisites` field of `list-ops/config.json`?
As per instructions the implementation uses no inbuilt functions/methods. I do call the `.len` property on an array though, but the `length` method could be used in its place.
All code has been tested with 2D arrays as input.
The `map` function has been changed to `map_of` to avoid a conflict with Vs built in map datatype.
All …
> feat(list-ops): add exercise list-ops to vlang track (resolves #144)

- config.json
- exercises/practice/custom-set/.docs/instructions.md
- exercises/practice/custom-set/.meta/config.json
- exercises/practice/custom-set/.meta/example.v
- exercises/practice/custom-set/.meta/tests.toml
- exercises/practice/custom-set/custom-set.v
- exercises/practice/custom-set/run_test.v
I'm using the preferred mechanism for building classes (`CustomSet.new()`). The union operation is changed to `@union` to avoid conflict with the `union` keyword.
Estimated this as a '5', difficulty wise.
> feat(test): port custom set exercise (resolves #148)

- exercises/practice/change/.meta/tests.toml
- exercises/practice/change/run_test.v
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/run_test.v
We sync the tests for
- change
- knapsack
- roman-numerals
> Sync tests

- exercises/practice/gigasecond/run_test.v
As mentioned in #232, this is to fix the Gigasecond tests (failed in test run https://github.com/exercism/vlang/actions/runs/11506925109).
This fixes the parsing of the date strings in the tests. According to the docs the, a couple of the dates are in ISO 8601 format rather than RFC 3339. RFC 3339 requires the time zone to be specified when the String contains a time. ISO 8601 doesn't have this requirment.
See:
- https://modules.vlang.io/time.html#parse_rfc3339
- https://ijmacd.github.io/rfc3339-iso8601/
When merging, I think it should be marked `[no important files changed]` as this commit shouldn't change any past test results.
> Fix time parsing in gigasecond tests

- exercises/practice/list-ops/run_test.v
- exercises/practice/parallel-letter-frequency/.meta/example.v
The commits in this PR fixes a build failure and a warning in the CI https://github.com/exercism/vlang/actions/runs/12798355176/job/35682210581?pr=236.
More specifically, the error is:
```
---- Testing... ----------------------------------------------------------------
Error: temp/run_test.v:34:44: error: array_init: no type specified (maybe: `[]Type{}` instead of `[]`)
32 | 
33 | fn test_concat_list_of_nested_lists() {
34 |     assert concat[[]int]([[[1], [2]], [[3]], [[]], [[4, 5, 6]]]) == [
|                                               ~~~
35 |         [1],
36 |         [2],
Error: temp/run_test.v:34:44: error: invalid void array element type
32 | 
33 | fn test_concat_list_of_nested_lists() {
34 |     assert concat[[]int]([[[1], [2]], [[3]], [[]], [[4, 5, 6]]]) == [
| …
```
> Update to work with Vlang 0.4.9

- exercises/practice/grains/run_test.v
The challenge does not specify that a specific error message should be thrown and requiring one might unintentionally hint at the solution. This change updates the test to check for an error code instead, allowing users more flexibility in how they implement error handling while still ensuring correctness.
> Replace specific error message check with error code check

- exercises/practice/custom-set/.meta/config.json
- exercises/practice/custom-set/.meta/example.v
This PR follows on from a [fix for a CI error](https://github.com/exercism/vlang/pull/264#issuecomment-3172609051) in custom-set in #264. 
According to [Vlang's documentation](https://github.com/exercism/vlang/pull/264#issuecomment-3172609051), a key of a map __must__ be one of these types:
- string
- rune
- integer
- float
- voidptr
It does not seem to support a generic type for as a key and V would normally give a compile error if an incorrect type is tried (see also https://github.com/vlang/v/issues/25084).
At the moment, the example still seems to work without this change, but I think making this change could help reduce the chance of the CI suddenly failing in the future, with future V releases.
> Replace map with array in custom-set example
