- config.json
- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/space-age/.meta/config.json
- exercises/practice/space-age/.meta/example.v
- exercises/practice/space-age/.meta/tests.toml
- exercises/practice/space-age/run_test.v
- exercises/practice/space-age/space-age.v
Implementing the [space age](https://github.com/exercism/problem-specifications/tree/main/exercises/space-age) problem
> feat: add space age exercise

- config.json
- exercises/practice/space-age/.meta/config.json
This should allow the configlet CI workflow to pass
Also adding some missing info to the config and fixing a typo in the config.json for space-age
> fix: add tags to config.json

- config.json
- exercises/practice/triangle/.docs/instructions.md
- exercises/practice/triangle/.meta/config.json
- exercises/practice/triangle/.meta/example.v
- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/triangle/run_test.v
- exercises/practice/triangle/triangle.v
Happy Thanksgiving! (if you celebrate that sort of thing :))
> feat: add Triangle exercise

- config.json
- exercises/practice/grains/.docs/instructions.md
- exercises/practice/grains/.meta/config.json
- exercises/practice/grains/.meta/example.v
- exercises/practice/grains/.meta/tests.toml
- exercises/practice/grains/grains.v
- exercises/practice/grains/run_test.v
found a better way to test to make sure a method that returns an error actually returns it, i'll update Space Age to match in a separate PR!
> feat: add Grains exercise

- exercises/practice/grade-school/.meta/config.json
- exercises/practice/grains/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/reverse-string/.meta/config.json
- exercises/practice/space-age/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
This runs the `bin/configlet fmt --update` command to format
all the exercise configs that need it.
> Reformat exercise configs

- exercises/practice/robot-name/.meta/example.v
Failure first noted [here](https://github.com/exercism/vlang/pull/40#issuecomment-1396982863) by @ErikSchierboom
> fix: robot name intermittent failure

- config.json
@ErikSchierboom @iHiD now that there is a [track icon for V](https://github.com/exercism/website-icons/pull/144) I believe the track is ready to be set active!! I'll be working on the test runner in the background but my understanding is that's not required to launch a track, correct?
> feat: set the track to active

- config.json
I realized that how I thought about difficulty levels was wrong (I thought 1=easy, 2=medium, 3=hard). Updating so what students see matches real difficulty levels
> fix: correct difficulty values

- config.json
- exercises/practice/accumulate/.docs/instructions.md
- exercises/practice/accumulate/.meta/config.json
- exercises/practice/accumulate/.meta/example.v
- exercises/practice/accumulate/.meta/tests.toml
- exercises/practice/accumulate/accumulate.v
- exercises/practice/accumulate/run_test.v
slightly different than most accumulate exercises because V is very strict: no overloading, no unknown return types, etc so it needs multiple function. I think this implementation covers the major aspects of the exercise!
> feat: add accumulate exercise

- config.json
- exercises/practice/collatz-conjecture/.docs/instructions.md
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/example.v
- exercises/practice/collatz-conjecture/.meta/tests.toml
- exercises/practice/collatz-conjecture/collatz-conjecture.v
- exercises/practice/collatz-conjecture/run_test.v
Adds the Collatz Conjecture practice exercise.
This is my first V program ever, please advise if everything looks idiomatic.
> Add Collatz Conjecture

- config.json
- exercises/practice/simple-linked-list/.docs/instructions.md
- exercises/practice/simple-linked-list/.meta/config.json
- exercises/practice/simple-linked-list/.meta/example.v
- exercises/practice/simple-linked-list/run_test.v
- exercises/practice/simple-linked-list/simple-linked-list.v
Last one from the 12in23 challenge.
> Add exercise `simple-linked-list`

- config.json
- exercises/practice/gigasecond/.docs/instructions.md
- exercises/practice/gigasecond/.docs/introduction.md
- exercises/practice/gigasecond/.meta/config.json
- exercises/practice/gigasecond/.meta/example.v
- exercises/practice/gigasecond/.meta/tests.toml
- exercises/practice/gigasecond/gigasecond.v
- exercises/practice/gigasecond/run_test.v
Implemented [Gigasecond](https://github.com/exercism/problem-specifications/tree/main/exercises/gigasecond) exercise.
1. I didn't understand [last test case](https://github.com/exercism/problem-specifications/blob/fc0e70d3c4b4dccf5a0ff422142b228bfd6a27fb/exercises/gigasecond/canonical-data.json#L70). Does it apply on V if yes how should I implement this?
2. For `../gigasecond/run_test.v`  I added some chain method for give output specific format is it okay or I should change test case expected string base on result.
> feat: Add exercise Gigasecond

- docs/RESOURCES.md
Added links to more V documentation
> Add links to more resources

- config.json
- exercises/practice/all-your-base/.docs/instructions.md
- exercises/practice/all-your-base/.meta/config.json
- exercises/practice/all-your-base/.meta/example.v
- exercises/practice/all-your-base/.meta/tests.toml
- exercises/practice/all-your-base/all-your-base.v
- exercises/practice/all-your-base/run_test.v
Add all-your-base practice exercise
Function and argument names are consistent with the Python port.
Test cases, including expected error strings, are generated from
https://github.com/exercism/problem-specifications/blob/main/exercises/all-your-base/canonical-data.json
Closes https://github.com/exercism/vlang/issues/75
> feat: Add exercise All Your Base (#75)

- config.json
- exercises/practice/bob/.docs/instructions.md
- exercises/practice/bob/.docs/introduction.md
- exercises/practice/bob/.meta/config.json
- exercises/practice/bob/.meta/example.v
- exercises/practice/bob/.meta/tests.toml
- exercises/practice/bob/bob.v
- exercises/practice/bob/run_test.v
Add bob practice exercise
Function and argument names are consistent with the Python port.
Test cases are generated from
https://github.com/exercism/problem-specifications/blob/main/exercises/bob/canonical-data.json
Closes https://github.com/exercism/vlang/issues/78
> feat: Add exercise Bob (#78)

- config.json
- exercises/practice/matching-brackets/.docs/instructions.md
- exercises/practice/matching-brackets/.meta/config.json
- exercises/practice/matching-brackets/.meta/example.v
- exercises/practice/matching-brackets/.meta/tests.toml
- exercises/practice/matching-brackets/matching-brackets.v
- exercises/practice/matching-brackets/run_test.v
Test cases are generated from
https://github.com/exercism/problem-specifications/blob/main/exercises/matching-brackets/canonical-data.json
Function and arguments names use snake_case, and are otherwise based on canonical data.
closes #80
> feat: Add exercise Matching Brackets (closes #80)

- config.json
- exercises/practice/change/.docs/instructions.md
- exercises/practice/change/.meta/config.json
- exercises/practice/change/.meta/example.v
- exercises/practice/change/.meta/tests.toml
- exercises/practice/change/change.v
- exercises/practice/change/run_test.v
Add `change` practice exercise
Test cases, including expected error strings, are generated from
https://github.com/exercism/problem-specifications/blob/main/exercises/change/canonical-data.json
Closes #81
> feat: Add exercise Change (closes #81)

- config.json
- exercises/practice/protein-translation/.docs/instructions.md
- exercises/practice/protein-translation/.meta/config.json
- exercises/practice/protein-translation/.meta/example.v
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/protein-translation.v
- exercises/practice/protein-translation/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/protein-translation/canonical-data.json
closes #77
> feat: Add exercise Protein Translation (#77)

- config.json
- exercises/practice/minesweeper/.docs/instructions.md
- exercises/practice/minesweeper/.meta/config.json
- exercises/practice/minesweeper/.meta/example.v
- exercises/practice/minesweeper/.meta/tests.toml
- exercises/practice/minesweeper/minesweeper.v
- exercises/practice/minesweeper/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/minesweeper/canonical-data.json
closes https://github.com/exercism/vlang/issues/85
> feat: Add exercise Minesweeper (closes #85)

- config.json
- exercises/practice/connect/.docs/instructions.md
- exercises/practice/connect/.meta/config.json
- exercises/practice/connect/.meta/example.v
- exercises/practice/connect/.meta/tests.toml
- exercises/practice/connect/connect.v
- exercises/practice/connect/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/connect/canonical-data.json
> feat: Add exercise Connect (closes #87)

- config.json
- exercises/practice/rectangles/.docs/instructions.md
- exercises/practice/rectangles/.meta/config.json
- exercises/practice/rectangles/.meta/example.v
- exercises/practice/rectangles/.meta/tests.toml
- exercises/practice/rectangles/rectangles.v
- exercises/practice/rectangles/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/rectangles/canonical-data.json
> feat: Add exercise Rectangles (closes #92)

- config.json
- exercises/practice/say/.docs/instructions.md
- exercises/practice/say/.meta/config.json
- exercises/practice/say/.meta/example.v
- exercises/practice/say/.meta/tests.toml
- exercises/practice/say/run_test.v
- exercises/practice/say/say.v
https://github.com/exercism/problem-specifications/blob/main/exercises/say/canonical-data.json
> feat: Add Say (closes #96)

- config.json
- exercises/practice/saddle-points/.docs/instructions.md
- exercises/practice/saddle-points/.docs/introduction.md
- exercises/practice/saddle-points/.meta/config.json
- exercises/practice/saddle-points/.meta/example.v
- exercises/practice/saddle-points/.meta/tests.toml
- exercises/practice/saddle-points/run_test.v
- exercises/practice/saddle-points/saddle-points.v
https://github.com/exercism/problem-specifications/blob/main/exercises/saddle-points/canonical-data.json
> feat: Add Saddle Points (closes #104)

- config.json
- exercises/practice/diamond/.docs/instructions.md
- exercises/practice/diamond/.meta/config.json
- exercises/practice/diamond/.meta/example.v
- exercises/practice/diamond/.meta/tests.toml
- exercises/practice/diamond/diamond.v
- exercises/practice/diamond/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/diamond/canonical-data.json
> feat: Add Diamond (closes #100)

- config.json
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/example.v
- exercises/practice/darts/.meta/tests.toml
- exercises/practice/darts/darts.v
- exercises/practice/darts/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/darts/canonical-data.json
> feat: Add Darts (closes #110)

- config.json
- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/largest-series-product/.meta/example.v
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/largest-series-product.v
- exercises/practice/largest-series-product/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/largest-series-product/canonical-data.json
> feat: Add Largest Series Product (closes #106)

- config.json
- exercises/practice/palindrome-products/.docs/instructions.md
- exercises/practice/palindrome-products/.meta/config.json
- exercises/practice/palindrome-products/.meta/example.v
- exercises/practice/palindrome-products/.meta/tests.toml
- exercises/practice/palindrome-products/palindrome-products.v
- exercises/practice/palindrome-products/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/palindrome-products/canonical-data.json
> feat: Add Palindrome Products (closes #115)

- config.json
- exercises/practice/rotational-cipher/.docs/instructions.md
- exercises/practice/rotational-cipher/.meta/config.json
- exercises/practice/rotational-cipher/.meta/example.v
- exercises/practice/rotational-cipher/.meta/tests.toml
- exercises/practice/rotational-cipher/rotational-cipher.v
- exercises/practice/rotational-cipher/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/rotational-cipher/canonical-data.json
closes https://github.com/exercism/vlang/issues/127
> feat: Add Rotational Cipher (closes #127)

- config.json
- exercises/practice/knapsack/.docs/instructions.md
- exercises/practice/knapsack/.meta/config.json
- exercises/practice/knapsack/.meta/example.v
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/knapsack/knapsack.v
- exercises/practice/knapsack/run_test.v
https://github.com/exercism/problem-specifications/blob/main/exercises/knapsack/canonical-data.json
> feat: Add Knapsack (closes #131)

- config.json
- exercises/practice/killer-sudoku-helper/.docs/instructions.md
- exercises/practice/killer-sudoku-helper/.meta/config.json
- exercises/practice/killer-sudoku-helper/.meta/example.v
- exercises/practice/killer-sudoku-helper/.meta/tests.toml
- exercises/practice/killer-sudoku-helper/killer-sudoku-helper.v
- exercises/practice/killer-sudoku-helper/run_test.v
Function and argument names, and test cases, are taken from https://github.com/exercism/problem-specifications/blob/main/exercises/killer-sudoku-helper/canonical-data.json
> feat: Add Killer Sudoku Helper (closes #135)

- config.json
- exercises/practice/crypto-square/.docs/instructions.md
- exercises/practice/crypto-square/.meta/config.json
- exercises/practice/crypto-square/.meta/example.v
- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/crypto-square/crypto-square.v
- exercises/practice/crypto-square/run_test.v
Function and argument names, and test cases, are taken from https://github.com/exercism/problem-specifications/blob/main/exercises/crypto-square/canonical-data.json
> feat: Add Crypto Square (closes #137)

- exercises/practice/binary-search/.docs/instructions.md
- exercises/practice/binary-search/.docs/introduction.md
- exercises/practice/linked-list/.docs/instructions.md
- exercises/practice/pangram/.docs/instructions.md
- exercises/practice/pangram/.docs/introduction.md
- exercises/practice/queen-attack/.docs/instructions.md
- exercises/practice/secret-handshake/.docs/instructions.md
- exercises/practice/secret-handshake/.meta/config.json
- exercises/practice/sieve/.docs/instructions.md
- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/two-fer/.docs/instructions.md
The results of running `./bin/configlet sync --docs --filepaths --metadata -uy`
> Sync metadata for exercises

- config.json
- exercises/practice/complex-numbers/.docs/instructions.md
- exercises/practice/complex-numbers/.meta/config.json
- exercises/practice/complex-numbers/.meta/example.v
- exercises/practice/complex-numbers/.meta/tests.toml
- exercises/practice/complex-numbers/complex-numbers.v
- exercises/practice/complex-numbers/run_test.v
Had to use some _close enough_  test functions (`assert_close_enough_complex`, `assert_close_enough_float`) to deal with rounding errors.
Hopefully the comments that go with the functions that mix real & complex numbers are enough.
I've given this a difficulty rating of '5' because of the amount of maths involved.
> feat(test): port complex numbers exercise (resolves #153)

- config.json
- exercises/practice/perfect-numbers/.docs/instructions.md
- exercises/practice/perfect-numbers/.meta/config.json
- exercises/practice/perfect-numbers/.meta/example.v
- exercises/practice/perfect-numbers/.meta/tests.toml
- exercises/practice/perfect-numbers/perfect-numbers.v
- exercises/practice/perfect-numbers/run_test.v
Estimated this to be a difficulty of '3', the same as Armstrong numbers. 
When checking to see if an error is returned I call the `msg()` method on the error object.
> feat(test): add perfect numbers exercise (resolves #158)

- config.json
- exercises/practice/pop-count/.docs/instructions.md
- exercises/practice/pop-count/.docs/introduction.md
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pop-count/.meta/example.v
- exercises/practice/pop-count/.meta/tests.toml
- exercises/practice/pop-count/pop-count.v
- exercises/practice/pop-count/run_test.v
This is a new exercise
https://forum.exercism.org/t/new-exercise-suggestion-pop-count/7632
https://github.com/exercism/problem-specifications/pull/2333
> feat: add pop-count exercise

- exercises/practice/acronym/.docs/instructions.md
- exercises/practice/affine-cipher/.docs/instructions.md
- exercises/practice/all-your-base/.docs/instructions.md
- exercises/practice/armstrong-numbers/.docs/instructions.md
- exercises/practice/binary-search/.docs/instructions.md
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/isogram/.docs/instructions.md
- exercises/practice/knapsack/.docs/instructions.md
- exercises/practice/list-ops/.docs/instructions.md
- exercises/practice/protein-translation/.docs/instructions.md
- exercises/practice/rotational-cipher/.docs/instructions.md
Update docs for the following exercises:
- acronym
- affine-cipher
- all-your-base
- armstrong-numbers
- binary-search
- darts
- isogram
- knapsack
- list-ops
- protein-translation
- rotational-cipher
> chore: sync exercise instructions

- exercises/practice/accumulate/.meta/config.json
- exercises/practice/clock/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pythagorean-triplet/.meta/config.json
Update metadata for the following exercises:
- accumulate
- clock
- hello-world
- meetup
- pop-count
- pythagorean-triplet
> chore: sync exercise metadata

- exercises/practice/rational-numbers/.meta/config.json
- exercises/practice/rational-numbers/.meta/example.v
- exercises/practice/rational-numbers/rational-numbers.v
The first argument to Rational.new is numerator.
The second argument is denominator.
resolves #181
> Exchange numerator and denominator

- .gitignore
The directory temp/ is used by bin/test
> git ignore temp/

- config.json
- exercises/practice/wordy/.docs/instructions.md
- exercises/practice/wordy/.meta/config.json
- exercises/practice/wordy/.meta/example.v
- exercises/practice/wordy/.meta/tests.toml
- exercises/practice/wordy/run_test.v
- exercises/practice/wordy/wordy.v
> feat: add wordy exercise

- config.json
- exercises/practice/circular-buffer/.docs/instructions.md
- exercises/practice/circular-buffer/.meta/config.json
- exercises/practice/circular-buffer/.meta/example.v
- exercises/practice/circular-buffer/.meta/tests.toml
- exercises/practice/circular-buffer/circular-buffer.v
- exercises/practice/circular-buffer/run_test.v
This change also applies configlet's formatting on the track's config.json.
> Add Circular Buffer exercise

- config.json
- exercises/practice/allergies/.docs/instructions.md
- exercises/practice/allergies/.meta/config.json
- exercises/practice/allergies/.meta/example.v
- exercises/practice/allergies/.meta/tests.toml
- exercises/practice/allergies/allergen.v
- exercises/practice/allergies/allergies.v
- exercises/practice/allergies/run_test.v
This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-03-19-allergies/9928)
> Add Allergies exercise

- config.json
- exercises/practice/zebra-puzzle/.docs/instructions.md
- exercises/practice/zebra-puzzle/.docs/introduction.md
- exercises/practice/zebra-puzzle/.meta/config.json
- exercises/practice/zebra-puzzle/.meta/example.v
- exercises/practice/zebra-puzzle/.meta/tests.toml
- exercises/practice/zebra-puzzle/run_test.v
- exercises/practice/zebra-puzzle/zebra-puzzle.v
This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-05-07-zebra-puzzle/10614)
> Add zebra puzzle exercise

- config.json
- exercises/practice/yacht/.docs/instructions.md
- exercises/practice/yacht/.docs/introduction.md
- exercises/practice/yacht/.meta/config.json
- exercises/practice/yacht/.meta/example.v
- exercises/practice/yacht/.meta/tests.toml
- exercises/practice/yacht/run_test.v
- exercises/practice/yacht/yacht.v
This is one of the [48in24](https://forum.exercism.org/t/48in24-exercise-06-11-yacht/11345) exercises
> Add yacht exercise

- exercises/practice/zebra-puzzle/.meta/example.v
> Ukranian => Ukrainian

- exercises/practice/affine-cipher/.docs/instructions.md
- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/eliuds-eggs/.docs/introduction.md
- exercises/practice/grains/.docs/instructions.md
- exercises/practice/grains/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/run_test.v
- exercises/practice/luhn/.docs/instructions.md
- exercises/practice/luhn/.docs/introduction.md
- exercises/practice/phone-number/.docs/instructions.md
- exercises/practice/saddle-points/.docs/instructions.md
- exercises/practice/sieve/.docs/instructions.md
>   Sync exercise instructions

- config.json
- exercises/practice/intergalactic-transmission/.docs/instructions.md
- exercises/practice/intergalactic-transmission/.docs/introduction.md
- exercises/practice/intergalactic-transmission/.meta/config.json
- exercises/practice/intergalactic-transmission/.meta/example.v
- exercises/practice/intergalactic-transmission/.meta/tests.toml
- exercises/practice/intergalactic-transmission/intergalactic-transmission.v
- exercises/practice/intergalactic-transmission/run_test.v
This PR adds the intergalactic transmission exercise from the [problem specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/intergalactic-transmission).
> Add intergalactic transmission exercise

- exercises/practice/meetup/.docs/instructions.md
> Sync exercise instructions
